// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("rescript/lib/js/belt_Id.js");
var Belt_Map = require("rescript/lib/js/belt_Map.js");
var Belt_Set = require("rescript/lib/js/belt_Set.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

var cmp = Caml_obj.caml_compare;

var CoordCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

var guessed = Belt_Set.fromArray([[
        1,
        1
      ]], CoordCmp);

var ships = Belt_Set.fromArray([
      [
        2,
        2
      ],
      [
        2,
        3
      ],
      [
        2,
        4
      ]
    ], CoordCmp);

function checkCoord(coord, guesses, ships) {
  if (Belt_Set.has(guesses, coord)) {
    console.log("already guessed");
  } else if (Belt_Set.has(ships, coord)) {
    console.log("hit");
  } else {
    console.log("miss");
  }
  
}

checkCoord([
      1,
      1
    ], guessed, ships);

checkCoord([
      0,
      0
    ], guessed, ships);

checkCoord([
      2,
      2
    ], guessed, ships);

checkCoord([
      -1,
      0
    ], guessed, ships);

var board = Belt_Map.fromArray([
      [
        [
          2,
          2
        ],
        /* Ship */0
      ],
      [
        [
          2,
          3
        ],
        /* Ship */0
      ],
      [
        [
          2,
          4
        ],
        /* Ship */0
      ],
      [
        [
          1,
          1
        ],
        /* Guessed */1
      ]
    ], CoordCmp);

function checkCoord$1(coord, map) {
  var match = Belt_Map.get(map, coord);
  if (match !== undefined) {
    if (match) {
      console.log("already guessed");
    } else {
      console.log("hit");
    }
  } else {
    console.log("miss");
  }
  
}

checkCoord$1([
      1,
      1
    ], board);

checkCoord$1([
      0,
      0
    ], board);

checkCoord$1([
      2,
      2
    ], board);

checkCoord$1([
      -1,
      0
    ], board);

exports.CoordCmp = CoordCmp;
exports.guessed = guessed;
exports.ships = ships;
exports.board = board;
exports.checkCoord = checkCoord$1;
/* CoordCmp Not a pure module */
