// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var JsModule = require("./js-module");

function getCurrentYear(prim) {
  return JsModule.getCurrentYear();
}

console.log(JsModule.getCurrentYear());

exports.getCurrentYear = getCurrentYear;
/*  Not a pure module */
