// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("rescript/lib/js/js_dict.js");
var Js_json = require("rescript/lib/js/js_json.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Webapi__Fetch = require("rescript-webapi/src/Webapi/Webapi__Fetch.bs.js");
var Webapi__Dom__HtmlInputElement = require("rescript-webapi/src/Webapi/Dom/Webapi__Dom__HtmlInputElement.bs.js");

var $$document = document;

function addEventListener(prim0, prim1, prim2) {
  prim0.addEventListener(prim1, prim2);
  
}

var submit = Belt_Option.getExn(Caml_option.nullable_to_opt($$document.getElementById("submit")));

var result = Belt_Option.getExn(Caml_option.nullable_to_opt($$document.getElementById("result")));

var input = Belt_Option.getExn(Belt_Option.flatMap(Caml_option.nullable_to_opt($$document.getElementById("name")), Webapi__Dom__HtmlInputElement.ofElement));

addEventListener(submit, "click", (function (param) {
        var payload = Webapi__Fetch.RequestInit.make(/* Post */2, {
                Accept: "application/json",
                "Content-Type": "application/json"
              }, Caml_option.some(Belt_Option.getExn(JSON.stringify({
                            name: input.value
                          }))), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined);
        console.log(payload);
        var __x = fetch("/hello", payload);
        var __x$1 = __x.then(function (prim) {
              return prim.json();
            });
        var __x$2 = __x$1.then(function (json) {
              return Promise.resolve(Belt_Option.getExn(Js_json.decodeObject(json)));
            });
        __x$2.then(function (obj) {
              var message = Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "message"), Js_json.decodeString));
              result.innerHTML = message;
              return Promise.resolve(undefined);
            });
        
      }));

/* document Not a pure module */
