// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("rescript/lib/js/belt_Id.js");
var Belt_Set = require("rescript/lib/js/belt_Set.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

function cmp(a, b) {
  if (Caml_obj.caml_lessthan(a, b)) {
    return -1;
  } else if (Caml_obj.caml_greaterthan(a, b)) {
    return 1;
  } else {
    return 0;
  }
}

var IntCmp = Belt_Id.MakeComparable({
      cmp: cmp
    });

var intSet = Belt_Set.fromArray([
      1,
      2,
      3,
      4,
      4
    ], IntCmp);

console.log(Belt_Set.toArray(intSet));

function cmp$1(a, b) {
  if (Caml_obj.caml_lessthan(a, b)) {
    return 1;
  } else if (Caml_obj.caml_greaterthan(a, b)) {
    return -1;
  } else {
    return 0;
  }
}

var RevIntCmp = Belt_Id.MakeComparable({
      cmp: cmp$1
    });

var revIntSet = Belt_Set.fromArray([
      1,
      2,
      3,
      4,
      4
    ], RevIntCmp);

console.log(Belt_Set.toArray(revIntSet));

exports.IntCmp = IntCmp;
exports.intSet = intSet;
exports.RevIntCmp = RevIntCmp;
exports.revIntSet = revIntSet;
/* IntCmp Not a pure module */
