// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

var a = [
  1,
  2,
  3
];

var b = Caml_array.get(a, 0);

exports.b = b;
/* No side effect */
