// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("rescript/lib/js/pervasives.js");

function $$double(x) {
  return (x << 1);
}

function isEven(x) {
  if (x === 0) {
    return true;
  } else {
    return isOdd(Pervasives.abs(x) - 1 | 0);
  }
}

function isOdd(x) {
  if (x === 0) {
    return false;
  } else {
    return isEven(Pervasives.abs(x) - 1 | 0);
  }
}

console.log(isOdd(100));

console.log(isEven(20));

console.log(1, 2, 3, 4);

console.log(1, 2, 3, 4);

console.log(1, 2, 3, 4);

console.log(1, 2, 3, 4);

var n = 800;

exports.$$double = $$double;
exports.n = n;
exports.isEven = isEven;
exports.isOdd = isOdd;
/*  Not a pure module */
