// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var path = require('path');
;

var joined = path.join("a", "b");

console.log(joined);

exports.joined = joined;
/*  Not a pure module */
