// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add1(x) {
  return x + 1 | 0;
}

// some large 64 bit number
var x = 1659303064418;
console.log(add1(x));
;

function add1float(x) {
  return x + 1;
}

// some large 64 bit number
var x = 1659303064418;
console.log(add1float(x));
;

exports.add1 = add1;
exports.add1float = add1float;
/*  Not a pure module */
