// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function addHealth(entity, n) {
    if (entity.TAG === 0) {
        return {TAG: 0, _0: entity._0, _1: entity._1 + n};
    } else if (entity.TAG === 1) {
        return {TAG: 1, _0: entity._0 + n};
    }
}
;

var entity1 = {
  TAG: /* Player */0,
  _0: "Danny",
  _1: 10
};

console.log(entity1);

console.log(addHealth(entity1, 5));

var entity2 = {
  TAG: /* Enemy */1,
  _0: 5
};

console.log(entity2);

console.log(addHealth(entity2, 5));

console.log(/* White */0);

console.log("White");

var polyEntity1 = {
  NAME: "Player",
  VAL: [
    "Danny",
    10
  ]
};

var polyEntity2 = {
  NAME: "Enemy",
  VAL: 5
};

var c1 = /* White */0;

var c2 = "White";

exports.entity1 = entity1;
exports.entity2 = entity2;
exports.polyEntity1 = polyEntity1;
exports.polyEntity2 = polyEntity2;
exports.c1 = c1;
exports.c2 = c2;
/*  Not a pure module */
