// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Int = require("rescript/lib/js/belt_Int.js");
var Caml_array = require("rescript/lib/js/caml_array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var input = Caml_array.get(process.argv, 2);

var year = Belt_Option.getExn(Belt_Int.fromString(input));

var isLeapYear = year % 400 === 0 ? true : (
    year % 100 === 0 ? false : year % 4 === 0
  );

if (isLeapYear) {
  console.log(input + " is a leap year");
} else {
  console.log(input + " is not a leap year");
}

exports.input = input;
exports.year = year;
exports.isLeapYear = isLeapYear;
/* input Not a pure module */
