// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("rescript/lib/js/belt_List.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function $$new(param) {
  return /* [] */0;
}

function push(stack, element) {
  return {
          hd: element,
          tl: stack
        };
}

function peek(stack) {
  if (stack) {
    return Caml_option.some(stack.hd);
  }
  
}

function pop(stack) {
  if (stack) {
    return stack.tl;
  } else {
    return stack;
  }
}

var size = Belt_List.size;

exports.$$new = $$new;
exports.push = push;
exports.peek = peek;
exports.pop = pop;
exports.size = size;
/* No side effect */
