// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

function $$double(arr) {
  return Belt_Array.map(arr, (function (x) {
                return (x << 1);
              }));
}

var myArr = $$double([
      1,
      2,
      3
    ]);

console.log(Belt_Array.get(myArr, 0));

exports.$$double = $$double;
exports.myArr = myArr;
/* myArr Not a pure module */
