// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("rescript/lib/js/js_json.js");
var Pervasives = require("rescript/lib/js/pervasives.js");

var myCat = {
  name: "Creamsicle",
  age: 13,
  owner: "Danny"
};

var serialized = Js_json.serializeExn(myCat);

console.log(serialized);

var parsed = JSON.parse("{ \"name\": \"Creamsicle\", \"age\": 13, \"owner\": \"Danny\" }");

console.log(parsed.name);

var c = {
  x: 1,
  y: 1
};

var c$p = Object.assign(c, {
      z: 2
    });

console.log(c);

console.log(c$p);

function manhattan(obj) {
  return Pervasives.abs(obj.x) + Pervasives.abs(obj.y) | 0;
}

var parsed$1 = JSON.parse("{ \"name\": \"Creamsicle\", \"age\": 13, \"owner\": \"Danny\" }");

var name = parsed$1.name;

exports.myCat = myCat;
exports.serialized = serialized;
exports.c = c;
exports.c$p = c$p;
exports.manhattan = manhattan;
exports.parsed = parsed$1;
exports.name = name;
/* serialized Not a pure module */
