// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var express = require('express');
var path = require('path');
;

var app = express();

app.use(express.json());

app.get("/", (function (param, response) {
        return response.sendFile(path.join(__dirname, "index.html"));
      }));

app.get("/script", (function (param, response) {
        return response.sendFile(path.join(__dirname, "Client1.bs.js"));
      }));

app.post("/hello", (function (request, response) {
        return response.send({
                    message: "Hello, " + request.body.name
                  });
      }));

app.listen(4000, (function (param) {
        console.log("Server is running on port 4000.");
        
      }));

exports.app = app;
/*  Not a pure module */
