// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Path = require("path");
var Express = require("express");

function express(prim) {
  return Express();
}

function json(prim) {
  return Express.json();
}

function listen(prim0, prim1, prim2) {
  return prim0.listen(prim1, prim2);
}

function use(prim0, prim1) {
  prim0.use(prim1);
  
}

function get(prim0, prim1, prim2) {
  prim0.get(prim1, prim2);
  
}

function post(prim0, prim1, prim2) {
  prim0.post(prim1, prim2);
  
}

function body(prim) {
  return prim.body;
}

function sendFile(prim0, prim1) {
  return prim0.sendFile(prim1);
}

function send(prim0, prim1) {
  return prim0.send(prim1);
}

var app = Express();

var prim1 = Express.json();

app.use(prim1);

get(app, "/", (function (param, response) {
        response.sendFile(Path.join(__dirname, "index.html"));
        
      }));

get(app, "/script", (function (param, response) {
        response.sendFile(Path.join(__dirname, "Client3.bs.js"));
        
      }));

post(app, "/hello", (function (request, response) {
        var body = request.body;
        response.send({
              message: "Hello, " + body.name
            });
        
      }));

app.listen(4000, (function (param) {
        console.log("Server is running on port 4000.");
        
      }));

exports.express = express;
exports.json = json;
exports.listen = listen;
exports.use = use;
exports.get = get;
exports.post = post;
exports.body = body;
exports.sendFile = sendFile;
exports.send = send;
exports.app = app;
/* app Not a pure module */
