// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_MutableQueue = require("rescript/lib/js/belt_MutableQueue.js");
var Belt_MutableStack = require("rescript/lib/js/belt_MutableStack.js");

var stack = Belt_MutableStack.make(undefined);

Belt_MutableStack.push(stack, 1);

Belt_MutableStack.push(stack, 2);

console.log(stack);

Belt_MutableStack.forEach(stack, (function (element) {
        console.log(element);
        
      }));

var q = Belt_MutableQueue.make(undefined);

Belt_MutableQueue.add(q, 1);

Belt_MutableQueue.add(q, 2);

console.log(q);

console.log(Belt_MutableQueue.toArray(q));

var s = Belt_MutableStack.make(undefined);

Belt_MutableStack.push(s, "a");

Belt_MutableStack.push(s, "b");

Belt_MutableStack.push(s, "c");

Belt_MutableStack.forEach(s, (function (element) {
        console.log(element);
        
      }));

exports.stack = stack;
exports.q = q;
exports.s = s;
/* stack Not a pure module */
